import vue from "@vitejs/plugin-vue";
import { defineConfig } from "electron-vite";
import { basename, resolve } from "path";
import { Plugin, UserConfigExport } from "vite";
import svgLoader from "vite-svg-loader";

const glob = (await import("fast-glob")).default;
const resolveOptions: UserConfigExport = {
	resolve: {
		alias: {
			"@renderer": resolve("src/renderer/src"),
			"@main": resolve("src/main"),
			"@preload": resolve("src/preload"),
			"@shared": resolve("src/shared"),
			"@translations": resolve("src/translations"),
			"@plugins": resolve("src/renderer-plugins"),
			"@": resolve("src"),
			"~": resolve("."),
			"discord-rpc": resolve("src/main/lib/discord-rpc/discord-rpc.ts"),
		},
	},
};
const externalizedEsmDeps = ["lodash-es", "@faker-js/faker", "@trpc-limiter/memory", "got", "encryption.js"];
const youtubeClientPlugins = glob.globSync("./src/renderer-plugins/youtube/*.plugin.ts").map((file) => {
	const name = basename(file, ".ts");
	return [name, file];
});

// Service Type Reference Generator Plugin for Electron-Vite
import fs from "fs";
import { camelCase } from "lodash-es";
import path from "path";

function generateServiceTypesPlugin(): Plugin {
	return {
		name: "generate-service-types",
		apply: "build",
		enforce: "pre",
		buildStart() {
			console.log("Generating service types...");
			const servicesDir = path.resolve(__dirname, "src/main/services");
			const outputFile = path.resolve(__dirname, "src/main/contracts/services.generated.d.ts");

			const files = fs.readdirSync(servicesDir).filter((file) => file.endsWith(".service.ts"));

			const imports: string[] = [];
			const exports: string[] = [];

			files.forEach((file, idx) => {
				const serviceName = path.basename(file, ".service.ts");
				const importAs = camelCase(`${serviceName}Provider`);
				imports.push(`import type ${importAs} from "@main/services/${serviceName}.service";`);
				exports.push(`"${serviceName}": ${importAs};`);
			});

			const typeDef = `// AUTO-GENERATED BY electron-vite-plugin
// biome-ignore-all format: generated file
${imports.join("\n")}

export interface ServiceTypeMap {
${exports.map((l) => "  " + l).join("\n")}
}
declare module "ytmd" {
	export interface BaseProviderNames extends ServiceTypeMap {}
}
export { };
`;

			fs.writeFileSync(outputFile, typeDef);
			if (exports.length) console.log("Service types generated successfully");
			else console.log("No services found");
		},
	};
}
export default defineConfig({
	main: {
		...resolveOptions,
		plugins: [generateServiceTypesPlugin()],
		build: {
			externalizeDeps: { exclude: [...externalizedEsmDeps] },
			rollupOptions: {
				input: {
					index: resolve(__dirname, "src/main/main.ts"),
				},
				output: {
					manualChunks: (id: string): any => {
						if (externalizedEsmDeps.find((d) => d === id)) return id;
						return null;
					},
				},
			},
		},
	},
	preload: {
		...resolveOptions,
		build: {
			externalizeDeps: { exclude: [...externalizedEsmDeps] },
			rollupOptions: {
				input: {
					youtube: resolve(__dirname, "src/preload/youtube.ts"),
					api: resolve(__dirname, "src/preload/api.ts"),
					login: resolve(__dirname, "src/preload/login.ts"),
					...Object.fromEntries(youtubeClientPlugins.map(([key, value]) => [`plugins/youtube/${key}`, value])),
				},
			},
		},
	},
	renderer: {
		...resolveOptions,
		plugins: [vue(), svgLoader()],
	},
});
