onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - 'electron-winstaller'
  - electron
  - esbuild
  - lefthook

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': set this to true or false
  bufferutil: true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
  utf-8-validate: true
