/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsAboutRouteImport } from './routes/_settings/about'
import { Route as SettingsApiIntegrationsApiRouteImport } from './routes/_settings/api-integrations/api'
import { Route as SettingsApiIntegrationsAuthenticationRouteImport } from './routes/_settings/api-integrations/authentication'
import { Route as SettingsApiIntegrationsIndexRouteImport } from './routes/_settings/api-integrations/index'
import { Route as SettingsApiIntegrationsLastfmRouteImport } from './routes/_settings/api-integrations/lastfm'
import { Route as SettingsApiIntegrationsRemoteRouteImport } from './routes/_settings/api-integrations/remote'
import { Route as SettingsApiIntegrationsRouteRouteImport } from './routes/_settings/api-integrations/route'
import { Route as SettingsApiIntegrationsStreamdeckRouteImport } from './routes/_settings/api-integrations/streamdeck'
import { Route as SettingsCustomCssRouteImport } from './routes/_settings/custom-css'
import { Route as SettingsDiscordRouteImport } from './routes/_settings/discord'
import { Route as SettingsIndexRouteImport } from './routes/_settings/index'
import { Route as SettingsIntegrationsRouteImport } from './routes/_settings/integrations'
import { Route as SettingsLastfmRouteImport } from './routes/_settings/lastfm'
import { Route as SettingsPlayerRouteImport } from './routes/_settings/player'
import { Route as SettingsRouteRouteImport } from './routes/_settings/route'
import { Route as SettingsStreamdeckRouteImport } from './routes/_settings/streamdeck'
import { Route as MiniplayerRouteImport } from './routes/miniplayer'
import { Route as RestartRouteImport } from './routes/restart'
import { Route as TaskviewRouteImport } from './routes/taskview'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as YoutubeLoadingRouteImport } from './routes/youtube/loading'
import { Route as YoutubeLoginNoticeRouteImport } from './routes/youtube/login-notice'
import { Route as YoutubeToolbarRouteImport } from './routes/youtube/toolbar'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniplayerRoute = MiniplayerRouteImport.update({
  id: '/miniplayer',
  path: '/miniplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const RestartRoute = RestartRouteImport.update({
  id: '/restart',
  path: '/restart',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskviewRoute = TaskviewRouteImport.update({
  id: '/taskview',
  path: '/taskview',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsApiIntegrationsRouteRoute =
  SettingsApiIntegrationsRouteRouteImport.update({
    id: '/api-integrations',
    path: '/api-integrations',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsCustomCssRoute = SettingsCustomCssRouteImport.update({
  id: '/custom-css',
  path: '/custom-css',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDiscordRoute = SettingsDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsLastfmRoute = SettingsLastfmRouteImport.update({
  id: '/lastfm',
  path: '/lastfm',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPlayerRoute = SettingsPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsStreamdeckRoute = SettingsStreamdeckRouteImport.update({
  id: '/streamdeck',
  path: '/streamdeck',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const YoutubeLoadingRoute = YoutubeLoadingRouteImport.update({
  id: '/youtube/loading',
  path: '/youtube/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeLoginNoticeRoute = YoutubeLoginNoticeRouteImport.update({
  id: '/youtube/login-notice',
  path: '/youtube/login-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeToolbarRoute = YoutubeToolbarRouteImport.update({
  id: '/youtube/toolbar',
  path: '/youtube/toolbar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiIntegrationsIndexRoute =
  SettingsApiIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsApiIntegrationsRouteRoute,
  } as any)
const SettingsApiIntegrationsApiRoute =
  SettingsApiIntegrationsApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => SettingsApiIntegrationsRouteRoute,
  } as any)
const SettingsApiIntegrationsAuthenticationRoute =
  SettingsApiIntegrationsAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => SettingsApiIntegrationsRouteRoute,
  } as any)
const SettingsApiIntegrationsLastfmRoute =
  SettingsApiIntegrationsLastfmRouteImport.update({
    id: '/lastfm',
    path: '/lastfm',
    getParentRoute: () => SettingsApiIntegrationsRouteRoute,
  } as any)
const SettingsApiIntegrationsRemoteRoute =
  SettingsApiIntegrationsRemoteRouteImport.update({
    id: '/remote',
    path: '/remote',
    getParentRoute: () => SettingsApiIntegrationsRouteRoute,
  } as any)
const SettingsApiIntegrationsStreamdeckRoute =
  SettingsApiIntegrationsStreamdeckRouteImport.update({
    id: '/streamdeck',
    path: '/streamdeck',
    getParentRoute: () => SettingsApiIntegrationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SettingsIndexRoute
  '/miniplayer': typeof MiniplayerRoute
  '/restart': typeof RestartRoute
  '/taskview': typeof TaskviewRoute
  '/update': typeof UpdateRoute
  '/api-integrations': typeof SettingsApiIntegrationsRouteRouteWithChildren
  '/about': typeof SettingsAboutRoute
  '/custom-css': typeof SettingsCustomCssRoute
  '/discord': typeof SettingsDiscordRoute
  '/integrations': typeof SettingsIntegrationsRoute
  '/lastfm': typeof SettingsLastfmRoute
  '/player': typeof SettingsPlayerRoute
  '/streamdeck': typeof SettingsStreamdeckRoute
  '/youtube/loading': typeof YoutubeLoadingRoute
  '/youtube/login-notice': typeof YoutubeLoginNoticeRoute
  '/youtube/toolbar': typeof YoutubeToolbarRoute
  '/api-integrations/api': typeof SettingsApiIntegrationsApiRoute
  '/api-integrations/authentication': typeof SettingsApiIntegrationsAuthenticationRoute
  '/api-integrations/lastfm': typeof SettingsApiIntegrationsLastfmRoute
  '/api-integrations/remote': typeof SettingsApiIntegrationsRemoteRoute
  '/api-integrations/streamdeck': typeof SettingsApiIntegrationsStreamdeckRoute
  '/api-integrations/': typeof SettingsApiIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/miniplayer': typeof MiniplayerRoute
  '/restart': typeof RestartRoute
  '/taskview': typeof TaskviewRoute
  '/update': typeof UpdateRoute
  '/about': typeof SettingsAboutRoute
  '/custom-css': typeof SettingsCustomCssRoute
  '/discord': typeof SettingsDiscordRoute
  '/integrations': typeof SettingsIntegrationsRoute
  '/lastfm': typeof SettingsLastfmRoute
  '/player': typeof SettingsPlayerRoute
  '/streamdeck': typeof SettingsStreamdeckRoute
  '/youtube/loading': typeof YoutubeLoadingRoute
  '/youtube/login-notice': typeof YoutubeLoginNoticeRoute
  '/youtube/toolbar': typeof YoutubeToolbarRoute
  '/': typeof SettingsIndexRoute
  '/api-integrations/api': typeof SettingsApiIntegrationsApiRoute
  '/api-integrations/authentication': typeof SettingsApiIntegrationsAuthenticationRoute
  '/api-integrations/lastfm': typeof SettingsApiIntegrationsLastfmRoute
  '/api-integrations/remote': typeof SettingsApiIntegrationsRemoteRoute
  '/api-integrations/streamdeck': typeof SettingsApiIntegrationsStreamdeckRoute
  '/api-integrations': typeof SettingsApiIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_settings': typeof SettingsRouteRouteWithChildren
  '/miniplayer': typeof MiniplayerRoute
  '/restart': typeof RestartRoute
  '/taskview': typeof TaskviewRoute
  '/update': typeof UpdateRoute
  '/_settings/api-integrations': typeof SettingsApiIntegrationsRouteRouteWithChildren
  '/_settings/about': typeof SettingsAboutRoute
  '/_settings/custom-css': typeof SettingsCustomCssRoute
  '/_settings/discord': typeof SettingsDiscordRoute
  '/_settings/integrations': typeof SettingsIntegrationsRoute
  '/_settings/lastfm': typeof SettingsLastfmRoute
  '/_settings/player': typeof SettingsPlayerRoute
  '/_settings/streamdeck': typeof SettingsStreamdeckRoute
  '/youtube/loading': typeof YoutubeLoadingRoute
  '/youtube/login-notice': typeof YoutubeLoginNoticeRoute
  '/youtube/toolbar': typeof YoutubeToolbarRoute
  '/_settings/': typeof SettingsIndexRoute
  '/_settings/api-integrations/api': typeof SettingsApiIntegrationsApiRoute
  '/_settings/api-integrations/authentication': typeof SettingsApiIntegrationsAuthenticationRoute
  '/_settings/api-integrations/lastfm': typeof SettingsApiIntegrationsLastfmRoute
  '/_settings/api-integrations/remote': typeof SettingsApiIntegrationsRemoteRoute
  '/_settings/api-integrations/streamdeck': typeof SettingsApiIntegrationsStreamdeckRoute
  '/_settings/api-integrations/': typeof SettingsApiIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/miniplayer'
    | '/restart'
    | '/taskview'
    | '/update'
    | '/api-integrations'
    | '/about'
    | '/custom-css'
    | '/discord'
    | '/integrations'
    | '/lastfm'
    | '/player'
    | '/streamdeck'
    | '/youtube/loading'
    | '/youtube/login-notice'
    | '/youtube/toolbar'
    | '/api-integrations/api'
    | '/api-integrations/authentication'
    | '/api-integrations/lastfm'
    | '/api-integrations/remote'
    | '/api-integrations/streamdeck'
    | '/api-integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/miniplayer'
    | '/restart'
    | '/taskview'
    | '/update'
    | '/about'
    | '/custom-css'
    | '/discord'
    | '/integrations'
    | '/lastfm'
    | '/player'
    | '/streamdeck'
    | '/youtube/loading'
    | '/youtube/login-notice'
    | '/youtube/toolbar'
    | '/'
    | '/api-integrations/api'
    | '/api-integrations/authentication'
    | '/api-integrations/lastfm'
    | '/api-integrations/remote'
    | '/api-integrations/streamdeck'
    | '/api-integrations'
  id:
    | '__root__'
    | '/_settings'
    | '/miniplayer'
    | '/restart'
    | '/taskview'
    | '/update'
    | '/_settings/api-integrations'
    | '/_settings/about'
    | '/_settings/custom-css'
    | '/_settings/discord'
    | '/_settings/integrations'
    | '/_settings/lastfm'
    | '/_settings/player'
    | '/_settings/streamdeck'
    | '/youtube/loading'
    | '/youtube/login-notice'
    | '/youtube/toolbar'
    | '/_settings/'
    | '/_settings/api-integrations/api'
    | '/_settings/api-integrations/authentication'
    | '/_settings/api-integrations/lastfm'
    | '/_settings/api-integrations/remote'
    | '/_settings/api-integrations/streamdeck'
    | '/_settings/api-integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  MiniplayerRoute: typeof MiniplayerRoute
  RestartRoute: typeof RestartRoute
  TaskviewRoute: typeof TaskviewRoute
  UpdateRoute: typeof UpdateRoute
  YoutubeLoadingRoute: typeof YoutubeLoadingRoute
  YoutubeLoginNoticeRoute: typeof YoutubeLoginNoticeRoute
  YoutubeToolbarRoute: typeof YoutubeToolbarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miniplayer': {
      id: '/miniplayer'
      path: '/miniplayer'
      fullPath: '/miniplayer'
      preLoaderRoute: typeof MiniplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restart': {
      id: '/restart'
      path: '/restart'
      fullPath: '/restart'
      preLoaderRoute: typeof RestartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taskview': {
      id: '/taskview'
      path: '/taskview'
      fullPath: '/taskview'
      preLoaderRoute: typeof TaskviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings/': {
      id: '/_settings/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/about': {
      id: '/_settings/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/api-integrations': {
      id: '/_settings/api-integrations'
      path: '/api-integrations'
      fullPath: '/api-integrations'
      preLoaderRoute: typeof SettingsApiIntegrationsRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/custom-css': {
      id: '/_settings/custom-css'
      path: '/custom-css'
      fullPath: '/custom-css'
      preLoaderRoute: typeof SettingsCustomCssRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/discord': {
      id: '/_settings/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof SettingsDiscordRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/integrations': {
      id: '/_settings/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/lastfm': {
      id: '/_settings/lastfm'
      path: '/lastfm'
      fullPath: '/lastfm'
      preLoaderRoute: typeof SettingsLastfmRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/player': {
      id: '/_settings/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof SettingsPlayerRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/streamdeck': {
      id: '/_settings/streamdeck'
      path: '/streamdeck'
      fullPath: '/streamdeck'
      preLoaderRoute: typeof SettingsStreamdeckRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/youtube/loading': {
      id: '/youtube/loading'
      path: '/youtube/loading'
      fullPath: '/youtube/loading'
      preLoaderRoute: typeof YoutubeLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/login-notice': {
      id: '/youtube/login-notice'
      path: '/youtube/login-notice'
      fullPath: '/youtube/login-notice'
      preLoaderRoute: typeof YoutubeLoginNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/toolbar': {
      id: '/youtube/toolbar'
      path: '/youtube/toolbar'
      fullPath: '/youtube/toolbar'
      preLoaderRoute: typeof YoutubeToolbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings/api-integrations/': {
      id: '/_settings/api-integrations/'
      path: '/'
      fullPath: '/api-integrations/'
      preLoaderRoute: typeof SettingsApiIntegrationsIndexRouteImport
      parentRoute: typeof SettingsApiIntegrationsRouteRoute
    }
    '/_settings/api-integrations/api': {
      id: '/_settings/api-integrations/api'
      path: '/api'
      fullPath: '/api-integrations/api'
      preLoaderRoute: typeof SettingsApiIntegrationsApiRouteImport
      parentRoute: typeof SettingsApiIntegrationsRouteRoute
    }
    '/_settings/api-integrations/authentication': {
      id: '/_settings/api-integrations/authentication'
      path: '/authentication'
      fullPath: '/api-integrations/authentication'
      preLoaderRoute: typeof SettingsApiIntegrationsAuthenticationRouteImport
      parentRoute: typeof SettingsApiIntegrationsRouteRoute
    }
    '/_settings/api-integrations/lastfm': {
      id: '/_settings/api-integrations/lastfm'
      path: '/lastfm'
      fullPath: '/api-integrations/lastfm'
      preLoaderRoute: typeof SettingsApiIntegrationsLastfmRouteImport
      parentRoute: typeof SettingsApiIntegrationsRouteRoute
    }
    '/_settings/api-integrations/remote': {
      id: '/_settings/api-integrations/remote'
      path: '/remote'
      fullPath: '/api-integrations/remote'
      preLoaderRoute: typeof SettingsApiIntegrationsRemoteRouteImport
      parentRoute: typeof SettingsApiIntegrationsRouteRoute
    }
    '/_settings/api-integrations/streamdeck': {
      id: '/_settings/api-integrations/streamdeck'
      path: '/streamdeck'
      fullPath: '/api-integrations/streamdeck'
      preLoaderRoute: typeof SettingsApiIntegrationsStreamdeckRouteImport
      parentRoute: typeof SettingsApiIntegrationsRouteRoute
    }
  }
}

interface SettingsApiIntegrationsRouteRouteChildren {
  SettingsApiIntegrationsApiRoute: typeof SettingsApiIntegrationsApiRoute
  SettingsApiIntegrationsAuthenticationRoute: typeof SettingsApiIntegrationsAuthenticationRoute
  SettingsApiIntegrationsLastfmRoute: typeof SettingsApiIntegrationsLastfmRoute
  SettingsApiIntegrationsRemoteRoute: typeof SettingsApiIntegrationsRemoteRoute
  SettingsApiIntegrationsStreamdeckRoute: typeof SettingsApiIntegrationsStreamdeckRoute
  SettingsApiIntegrationsIndexRoute: typeof SettingsApiIntegrationsIndexRoute
}

const SettingsApiIntegrationsRouteRouteChildren: SettingsApiIntegrationsRouteRouteChildren =
  {
    SettingsApiIntegrationsApiRoute: SettingsApiIntegrationsApiRoute,
    SettingsApiIntegrationsAuthenticationRoute:
      SettingsApiIntegrationsAuthenticationRoute,
    SettingsApiIntegrationsLastfmRoute: SettingsApiIntegrationsLastfmRoute,
    SettingsApiIntegrationsRemoteRoute: SettingsApiIntegrationsRemoteRoute,
    SettingsApiIntegrationsStreamdeckRoute:
      SettingsApiIntegrationsStreamdeckRoute,
    SettingsApiIntegrationsIndexRoute: SettingsApiIntegrationsIndexRoute,
  }

const SettingsApiIntegrationsRouteRouteWithChildren =
  SettingsApiIntegrationsRouteRoute._addFileChildren(
    SettingsApiIntegrationsRouteRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingsApiIntegrationsRouteRoute: typeof SettingsApiIntegrationsRouteRouteWithChildren
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsCustomCssRoute: typeof SettingsCustomCssRoute
  SettingsDiscordRoute: typeof SettingsDiscordRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsLastfmRoute: typeof SettingsLastfmRoute
  SettingsPlayerRoute: typeof SettingsPlayerRoute
  SettingsStreamdeckRoute: typeof SettingsStreamdeckRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsApiIntegrationsRouteRoute:
    SettingsApiIntegrationsRouteRouteWithChildren,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsCustomCssRoute: SettingsCustomCssRoute,
  SettingsDiscordRoute: SettingsDiscordRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsLastfmRoute: SettingsLastfmRoute,
  SettingsPlayerRoute: SettingsPlayerRoute,
  SettingsStreamdeckRoute: SettingsStreamdeckRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  MiniplayerRoute: MiniplayerRoute,
  RestartRoute: RestartRoute,
  TaskviewRoute: TaskviewRoute,
  UpdateRoute: UpdateRoute,
  YoutubeLoadingRoute: YoutubeLoadingRoute,
  YoutubeLoginNoticeRoute: YoutubeLoginNoticeRoute,
  YoutubeToolbarRoute: YoutubeToolbarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
