/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsAboutRouteImport } from './routes/_settings/about'
import { Route as SettingsCustomCssRouteImport } from './routes/_settings/custom-css'
import { Route as SettingsDiscordRouteImport } from './routes/_settings/discord'
import { Route as SettingsIndexRouteImport } from './routes/_settings/index'
import { Route as SettingsIntegrationsRouteImport } from './routes/_settings/integrations'
import { Route as SettingsPlayerRouteImport } from './routes/_settings/player'
import { Route as SettingsRouteRouteImport } from './routes/_settings/route'
import { Route as SettingsStreamdeckRouteImport } from './routes/_settings/streamdeck'
import { Route as MiniplayerRouteImport } from './routes/miniplayer'
import { Route as RestartRouteImport } from './routes/restart'
import { Route as TaskviewRouteImport } from './routes/taskview'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as YoutubeLoadingRouteImport } from './routes/youtube/loading'
import { Route as YoutubeLoginNoticeRouteImport } from './routes/youtube/login-notice'
import { Route as YoutubeToolbarRouteImport } from './routes/youtube/toolbar'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniplayerRoute = MiniplayerRouteImport.update({
  id: '/miniplayer',
  path: '/miniplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const RestartRoute = RestartRouteImport.update({
  id: '/restart',
  path: '/restart',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskviewRoute = TaskviewRouteImport.update({
  id: '/taskview',
  path: '/taskview',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCustomCssRoute = SettingsCustomCssRouteImport.update({
  id: '/custom-css',
  path: '/custom-css',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDiscordRoute = SettingsDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPlayerRoute = SettingsPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsStreamdeckRoute = SettingsStreamdeckRouteImport.update({
  id: '/streamdeck',
  path: '/streamdeck',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const YoutubeLoadingRoute = YoutubeLoadingRouteImport.update({
  id: '/youtube/loading',
  path: '/youtube/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeLoginNoticeRoute = YoutubeLoginNoticeRouteImport.update({
  id: '/youtube/login-notice',
  path: '/youtube/login-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeToolbarRoute = YoutubeToolbarRouteImport.update({
  id: '/youtube/toolbar',
  path: '/youtube/toolbar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SettingsIndexRoute
  '/miniplayer': typeof MiniplayerRoute
  '/restart': typeof RestartRoute
  '/taskview': typeof TaskviewRoute
  '/update': typeof UpdateRoute
  '/about': typeof SettingsAboutRoute
  '/custom-css': typeof SettingsCustomCssRoute
  '/discord': typeof SettingsDiscordRoute
  '/integrations': typeof SettingsIntegrationsRoute
  '/player': typeof SettingsPlayerRoute
  '/streamdeck': typeof SettingsStreamdeckRoute
  '/youtube/loading': typeof YoutubeLoadingRoute
  '/youtube/login-notice': typeof YoutubeLoginNoticeRoute
  '/youtube/toolbar': typeof YoutubeToolbarRoute
}
export interface FileRoutesByTo {
  '/miniplayer': typeof MiniplayerRoute
  '/restart': typeof RestartRoute
  '/taskview': typeof TaskviewRoute
  '/update': typeof UpdateRoute
  '/about': typeof SettingsAboutRoute
  '/custom-css': typeof SettingsCustomCssRoute
  '/discord': typeof SettingsDiscordRoute
  '/integrations': typeof SettingsIntegrationsRoute
  '/player': typeof SettingsPlayerRoute
  '/streamdeck': typeof SettingsStreamdeckRoute
  '/youtube/loading': typeof YoutubeLoadingRoute
  '/youtube/login-notice': typeof YoutubeLoginNoticeRoute
  '/youtube/toolbar': typeof YoutubeToolbarRoute
  '/': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_settings': typeof SettingsRouteRouteWithChildren
  '/miniplayer': typeof MiniplayerRoute
  '/restart': typeof RestartRoute
  '/taskview': typeof TaskviewRoute
  '/update': typeof UpdateRoute
  '/_settings/about': typeof SettingsAboutRoute
  '/_settings/custom-css': typeof SettingsCustomCssRoute
  '/_settings/discord': typeof SettingsDiscordRoute
  '/_settings/integrations': typeof SettingsIntegrationsRoute
  '/_settings/player': typeof SettingsPlayerRoute
  '/_settings/streamdeck': typeof SettingsStreamdeckRoute
  '/youtube/loading': typeof YoutubeLoadingRoute
  '/youtube/login-notice': typeof YoutubeLoginNoticeRoute
  '/youtube/toolbar': typeof YoutubeToolbarRoute
  '/_settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/miniplayer'
    | '/restart'
    | '/taskview'
    | '/update'
    | '/about'
    | '/custom-css'
    | '/discord'
    | '/integrations'
    | '/player'
    | '/streamdeck'
    | '/youtube/loading'
    | '/youtube/login-notice'
    | '/youtube/toolbar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/miniplayer'
    | '/restart'
    | '/taskview'
    | '/update'
    | '/about'
    | '/custom-css'
    | '/discord'
    | '/integrations'
    | '/player'
    | '/streamdeck'
    | '/youtube/loading'
    | '/youtube/login-notice'
    | '/youtube/toolbar'
    | '/'
  id:
    | '__root__'
    | '/_settings'
    | '/miniplayer'
    | '/restart'
    | '/taskview'
    | '/update'
    | '/_settings/about'
    | '/_settings/custom-css'
    | '/_settings/discord'
    | '/_settings/integrations'
    | '/_settings/player'
    | '/_settings/streamdeck'
    | '/youtube/loading'
    | '/youtube/login-notice'
    | '/youtube/toolbar'
    | '/_settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  MiniplayerRoute: typeof MiniplayerRoute
  RestartRoute: typeof RestartRoute
  TaskviewRoute: typeof TaskviewRoute
  UpdateRoute: typeof UpdateRoute
  YoutubeLoadingRoute: typeof YoutubeLoadingRoute
  YoutubeLoginNoticeRoute: typeof YoutubeLoginNoticeRoute
  YoutubeToolbarRoute: typeof YoutubeToolbarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miniplayer': {
      id: '/miniplayer'
      path: '/miniplayer'
      fullPath: '/miniplayer'
      preLoaderRoute: typeof MiniplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restart': {
      id: '/restart'
      path: '/restart'
      fullPath: '/restart'
      preLoaderRoute: typeof RestartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taskview': {
      id: '/taskview'
      path: '/taskview'
      fullPath: '/taskview'
      preLoaderRoute: typeof TaskviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings/': {
      id: '/_settings/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/about': {
      id: '/_settings/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/custom-css': {
      id: '/_settings/custom-css'
      path: '/custom-css'
      fullPath: '/custom-css'
      preLoaderRoute: typeof SettingsCustomCssRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/discord': {
      id: '/_settings/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof SettingsDiscordRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/integrations': {
      id: '/_settings/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/player': {
      id: '/_settings/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof SettingsPlayerRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_settings/streamdeck': {
      id: '/_settings/streamdeck'
      path: '/streamdeck'
      fullPath: '/streamdeck'
      preLoaderRoute: typeof SettingsStreamdeckRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/youtube/loading': {
      id: '/youtube/loading'
      path: '/youtube/loading'
      fullPath: '/youtube/loading'
      preLoaderRoute: typeof YoutubeLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/login-notice': {
      id: '/youtube/login-notice'
      path: '/youtube/login-notice'
      fullPath: '/youtube/login-notice'
      preLoaderRoute: typeof YoutubeLoginNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/toolbar': {
      id: '/youtube/toolbar'
      path: '/youtube/toolbar'
      fullPath: '/youtube/toolbar'
      preLoaderRoute: typeof YoutubeToolbarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsCustomCssRoute: typeof SettingsCustomCssRoute
  SettingsDiscordRoute: typeof SettingsDiscordRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsPlayerRoute: typeof SettingsPlayerRoute
  SettingsStreamdeckRoute: typeof SettingsStreamdeckRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsCustomCssRoute: SettingsCustomCssRoute,
  SettingsDiscordRoute: SettingsDiscordRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsPlayerRoute: SettingsPlayerRoute,
  SettingsStreamdeckRoute: SettingsStreamdeckRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  MiniplayerRoute: MiniplayerRoute,
  RestartRoute: RestartRoute,
  TaskviewRoute: TaskviewRoute,
  UpdateRoute: UpdateRoute,
  YoutubeLoadingRoute: YoutubeLoadingRoute,
  YoutubeLoginNoticeRoute: YoutubeLoginNoticeRoute,
  YoutubeToolbarRoute: YoutubeToolbarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
