export const API_ROUTES = {
	TRACK_CURRENT: "api/track",
	TRACK_CURRENT_STATE: "api/track/state",
	TRACK_LIKE: "api/track/like",
	TRACK_DISLIKE: "api/track/dislike",
	TRACK_ACCENT: "api/track/accent",
	TRACK_CONTROL_NEXT: "api/track/next",
	TRACK_CONTROL_PREV: "api/track/prev",
	TRACK_CONTROL_FORWARD: "api/track/forward",
	TRACK_CONTROL_BACKWARD: "api/track/backward",
	TRACK_CONTROL_PLAY: "api/track/play",
	TRACK_CONTROL_SEEK: "api/track/seek",
	TRACK_CONTROL_PAUSE: "api/track/pause",
	TRACK_CONTROL_TOGGLE_PLAY: "api/track/toggle-play-state",
	TRACK_CONTROL_REPEAT: "api/track/repeat",
	TRACK_CONTROL_SHUFFLE: "api/track/shuffle",
	TRACK_CONTROL_VOLUME: "api/track/volume",
	TRACK_CONTROL_VOLUME_UP: "api/track/volume-up",
	TRACK_CONTROL_VOLUME_DOWN: "api/track/volume-down",
	TRACK_SOCKET: "api/socket",
	NAV_WATCH: "api/nav/watch",
	NAV_PLAYLIST: "api/nav/playlist",
	NAV_CHANNEL: "api/nav/channel",
	NAV_QUEUE: "api/nav/queue",
	NAV_QUEUE_LIST: "api/nav/queue/list",
	NAV_QUEUE_CLEAR: "api/nav/queue/clear",
	NAV_OPEN: "api/nav/open",
	NAV_HOME: "api/nav/home",
	AUTH_REQUEST_CODE: "api/auth/requestcode",
	AUTH_REQUEST: "api/auth/request",
} as const;

export const API_AUTH_EVENTS = {
	PENDING: "auth.pending",
	RESOLVED: "auth.resolved",
	CLIENTS: "auth.clients",
} as const;
const IPC_EVENT_NAMES = {
	SERVER_SETTINGS_CHANGE: "settingsProvider.change",
	TRACK_CHANGE: "track:change",
	TRACK_LIKE_STATE: "track:like-state",
	TRACK_PLAYSTATE: "track:play-state",
	TRACK_PLAYSTATE_PROGRESS: "track:play-state-progress",
	TRACK_CONTROL: "track:control",
	APP_UPDATE: "app.update",
	APP_UPDATE_CHECKING: "app.updateChecking",
	APP_UPDATE_PROGRESS: "app.updateProgress",
	APP_UPDATE_DOWNLOADED: "app.updateDownloaded",
	LAST_FM_AUTHORIZE: "lastfm.authorize",
	LAST_FM_STATUS: "lastfm.status",
	LAST_FM_PROFILE: "lastfm.profile",
	LAST_FM_TOGGLE: "lastfm.toggle",
	LAST_FM_SUBMIT_STATE: "lastfm.stateObserver",
	APP_TOAST: "app.toast",
	...API_ROUTES,
} as const;
export default IPC_EVENT_NAMES;
