// AUTO-GENERATED BY electron-vite-plugin
// biome-ignore-all format: generated file
import type apiProvider from "@main/services/api.service";
import type appProvider from "@main/services/app.service";
import type customCssProvider from "@main/services/customCss.service";
import type discordProvider from "@main/services/discord.service";
import type eventProvider from "@main/services/event.service";
import type lastfmProvider from "@main/services/lastfm.service";
import type mediaControlProvider from "@main/services/mediaControl.service";
import type miniPlayerProvider from "@main/services/miniPlayer.service";
import type navigationProvider from "@main/services/navigation.service";
import type settingsProvider from "@main/services/settings.service";
import type startupProvider from "@main/services/startup.service";
import type touchbarProvider from "@main/services/touchbar.service";
import type trackProvider from "@main/services/track.service";
import type trayProvider from "@main/services/tray.service";
import type updateProvider from "@main/services/update.service";
import type volumeRatioProvider from "@main/services/volumeRatio.service";
import type winControlProvider from "@main/services/winControl.service";
import type windowProvider from "@main/services/window.service";
import type youtubeProvider from "@main/services/youtube.service";

export interface ServiceTypeMap {
  "api": apiProvider;
  "app": appProvider;
  "customCss": customCssProvider;
  "discord": discordProvider;
  "event": eventProvider;
  "lastfm": lastfmProvider;
  "mediaControl": mediaControlProvider;
  "miniPlayer": miniPlayerProvider;
  "navigation": navigationProvider;
  "settings": settingsProvider;
  "startup": startupProvider;
  "touchbar": touchbarProvider;
  "track": trackProvider;
  "tray": trayProvider;
  "update": updateProvider;
  "volumeRatio": volumeRatioProvider;
  "winControl": winControlProvider;
  "window": windowProvider;
  "youtube": youtubeProvider;
}
declare module "ytmd" {
	export interface BaseProviderNames extends ServiceTypeMap {}
}
export { };
