import tailwindcss from "@tailwindcss/vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import react from "@vitejs/plugin-react-swc";
import { defineConfig } from "electron-vite";
import fs from "fs";
import { camelCase } from "lodash-es";
import { createRequire } from "module";
import path, { basename, resolve } from "path";
import { type AliasOptions, type Plugin, type UserConfigExport } from "vite";
import svgr from "vite-plugin-svgr";
import { ytmdSidecarWatchPlugin, ytmdWorld0BuildPlugin } from "./vite-plugins/sidecar-builds";

const require = createRequire(import.meta.url);
const glob = (await import("fast-glob")).default;

/**
 * Path aliases mirror tsconfig.node.json / tsconfig.web.json.
 * `@` is process-specific: main→src/main, renderer→src/renderer/src.
 */
const sharedAliases: AliasOptions = {
	"@main": resolve("src/main"),
  "@renderer": resolve("src/renderer/src"),
	"@routers": resolve("src/main/trpc/routers"),
	"@preload": resolve("src/preload"),
	"@shared": resolve("src/shared"),
	"@translations": resolve("src/translations"),
	"@plugins": resolve("src/renderer-plugins"),
	"~": resolve("."),
	"discord-rpc": resolve("src/main/lib/discord-rpc/discord-rpc.ts"),
};

/** tsconfig.node.json */
const mainResolve: UserConfigExport = {
	resolve: {
		alias: {
			...sharedAliases,
			"@": resolve("src/main"),
		},
	},
};

/** tsconfig.web.json */
const rendererResolve: UserConfigExport = {
	resolve: {
		alias: {
			...sharedAliases,
			"@": resolve("src/renderer/src"),
		},
	},
};

const externalizedEsmDeps = ["lodash-es", "@faker-js/faker", "@trpc-limiter/memory", "got", "encryption.js"];
/** Bundle into main — avoid asar nested node_modules holes (Express/ee-first class). */
const bundleIntoMain = ["hono", "@hono/node-server", "ws"];
/**
 * Bundle into youtube preload — lyrics React UI must not require() Node react.
 * Measured (prod minify): react-vendor ~584KB + lyrics.plugin ~20KB (was ~1.6MB monolithic).
 */
const bundleIntoPreload = ["react", "react-dom", "react/jsx-runtime", "scheduler"];
const youtubeClientPlugins = glob.globSync("./src/renderer-plugins/youtube/*.plugin.ts").map((file) => {
	const name = basename(file, ".ts");
	return [name, file];
});

function isReactPreloadModule(id: string): boolean {
	return /[/\\]node_modules[/\\](react|react-dom|scheduler)([/\\]|$)/.test(id);
}

function generateServiceTypesPlugin(): Plugin {
	const writeServiceTypes = () => {
		const routersDir = path.resolve(__dirname, "src/main/trpc/routers");
		const outputFile = path.resolve(__dirname, "src/main/contracts/services.generated.d.ts");

		if (!fs.existsSync(routersDir)) {
			console.warn("[generate-service-types] routers dir missing:", routersDir);
			return;
		}

		const folders = fs
			.readdirSync(routersDir, { withFileTypes: true })
			.filter((d) => d.isDirectory())
			.map((d) => d.name)
			.filter((name) => fs.existsSync(path.join(routersDir, name, "service.ts")))
			.sort();

		const imports: string[] = [];
		const exports: string[] = [];

		for (const serviceName of folders) {
			const serviceFile = path.join(routersDir, serviceName, "service.ts");
			const src = fs.readFileSync(serviceFile, "utf8");
			const importAs = camelCase(`${serviceName}Provider`);
			const modulePath = `@routers/${serviceName}/service`;

			if (/export\s+default\s+class\s+\w+/.test(src)) {
				imports.push(`import type ${importAs} from "${modulePath}";`);
			} else {
				const named = src.match(/export\s+class\s+(\w+)/);
				if (!named) continue;
				imports.push(`import type { ${named[1]} as ${importAs} } from "${modulePath}";`);
			}

			exports.push(`"${serviceName}": ${importAs};`);
		}

		const typeDef = `// AUTO-GENERATED BY electron-vite-plugin
// biome-ignore-all format: generated file
${imports.join("\n")}

export interface ServiceTypeMap {
${exports.map((l) => "  " + l).join("\n")}
}
declare module "ytmd" {
	export interface BaseProviderNames extends ServiceTypeMap {}
  export type ServiceName = keyof ServiceTypeMap;
  export type ProviderNameKey = keyof BaseProviderNames | ({} & string);
}
export { };
`;

		fs.writeFileSync(outputFile, typeDef);
		console.log(`[generate-service-types] ${exports.length} services → ${path.relative(__dirname, outputFile)}`);
	};

	return {
		name: "generate-service-types",
		enforce: "pre",
		configResolved() {
			writeServiceTypes();
		},
		buildStart() {
			writeServiceTypes();
		},
	};
}

export default defineConfig({
	main: {
		...mainResolve,
		plugins: [generateServiceTypesPlugin()],
		build: {
			externalizeDeps: { exclude: [...externalizedEsmDeps, ...bundleIntoMain] },
			rollupOptions: {
				input: {
					index: resolve(__dirname, "src/main/main.ts"),
				},
				output: {
					manualChunks: (id: string): any => {
						if (externalizedEsmDeps.find((d) => d === id)) return id;
						return null;
					},
				},
			},
		},
	},
	preload: {
		...mainResolve,
		plugins: [ytmdWorld0BuildPlugin(), react()],
		build: {
			minify: "esbuild",
			externalizeDeps: { exclude: [...externalizedEsmDeps, ...bundleIntoMain, ...bundleIntoPreload] },
			rollupOptions: {
				input: {
					youtube: resolve(__dirname, "src/preload/youtube.ts"),
					api: resolve(__dirname, "src/preload/api.ts"),
					login: resolve(__dirname, "src/preload/login.ts"),
					...Object.fromEntries(youtubeClientPlugins.map(([key, value]) => [`plugins/youtube/${key}`, value])),
				},
				output: {
					manualChunks(id: string): string | null | undefined {
						if (isReactPreloadModule(id)) return "react-vendor";
						return null;
					},
				},
			},
		},
	},
	renderer: {
		...rendererResolve,
		server: {
			hmr: {
				overlay: true,
			},
		},
		plugins: [
			ytmdSidecarWatchPlugin(),
			tanstackRouter({
				target: "react",
				autoCodeSplitting: true,
				routesDirectory: "./src/routes",
				generatedRouteTree: "./src/routeTree.gen.ts",
			}),
			react({
				plugins: [[require.resolve("@swc/plugin-styled-jsx"), {}]],
			}),
			svgr(),
			tailwindcss(),
		],
	},
});
