// AUTO-GENERATED BY electron-vite-plugin
// biome-ignore-all format: generated file
import type apiProvider from "@routers/api/service";
import type appProvider from "@routers/app/service";
import type authProvider from "@routers/auth/service";
import type deeplinkProvider from "@routers/deeplink/service";
import type discordProvider from "@routers/discord/service";
import type eventProvider from "@routers/event/service";
import type lastfmProvider from "@routers/lastfm/service";
import type lyricsProvider from "@routers/lyrics/service";
import type mediaControlProvider from "@routers/mediaControl/service";
import type navigationProvider from "@routers/navigation/service";
import type settingsProvider from "@routers/settings/service";
import type shortcutProvider from "@routers/shortcut/service";
import type startupProvider from "@routers/startup/service";
import type themesProvider from "@routers/themes/service";
import type touchbarProvider from "@routers/touchbar/service";
import type { TrackService as trackProvider } from "@routers/track/service";
import type trayProvider from "@routers/tray/service";
import type trayViewProvider from "@routers/trayView/service";
import type updateProvider from "@routers/update/service";
import type volumeRatioProvider from "@routers/volumeRatio/service";
import type winControlProvider from "@routers/winControl/service";
import type windowProvider from "@routers/window/service";
import type youtubeProvider from "@routers/youtube/service";

export interface ServiceTypeMap {
  "api": apiProvider;
  "app": appProvider;
  "auth": authProvider;
  "deeplink": deeplinkProvider;
  "discord": discordProvider;
  "event": eventProvider;
  "lastfm": lastfmProvider;
  "lyrics": lyricsProvider;
  "mediaControl": mediaControlProvider;
  "navigation": navigationProvider;
  "settings": settingsProvider;
  "shortcut": shortcutProvider;
  "startup": startupProvider;
  "themes": themesProvider;
  "touchbar": touchbarProvider;
  "track": trackProvider;
  "tray": trayProvider;
  "trayView": trayViewProvider;
  "update": updateProvider;
  "volumeRatio": volumeRatioProvider;
  "winControl": winControlProvider;
  "window": windowProvider;
  "youtube": youtubeProvider;
}
declare module "ytmd" {
	export interface BaseProviderNames extends ServiceTypeMap {}
  export type ServiceName = keyof ServiceTypeMap;
  export type ProviderNameKey = keyof BaseProviderNames | ({} & string);
}
export { };
